///////////////////////////////////////////////////////////
//  Voiture2.cs
//  Implementation of the Class Voiture
//  Generated by Enterprise Architect
//  Created on:      12-nov.-2018 12:56:38
//  Original author: CRM
///////////////////////////////////////////////////////////




/// <summary>
/// démarrer() :void
/// arrêter () : void
/// avancer () :void
/// </summary>
private class Voiture 

{
	public Moteur m_Moteur;
	public Roues m_Roues;

	public Voiture()
    {

	}

	~Voiture()
    {

	}

	public virtual void Dispose()
    {

	}

	public void démarrer()
    {

	}

	public void arrêter()
    {

	}

	public void avancer()
    {

	}

}//end Voiture